BASE_URL = 'http://www.ftn.uns.ac.rs'
START_URL = '/n1430118859/fakultet-tehnickih-nauka'
DATA = './data'
STUDY_PROGRAMS_DATA = DATA + '/study_programs.csv'
PERSONS_DATA = DATA + '/persons.csv'
SUBJECTS_DATA = DATA + '/subjects.csv'
